#!/usr/bin/env python3
"""Render nfpm package specs from cdt-manifest.toml."""

from __future__ import annotations

import argparse
import sys
try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore[no-redef]
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = ROOT / "cdt-manifest.toml"


def load_binaries() -> list[str]:
    manifest = tomllib.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    binaries = ["cdt"]
    for component in manifest["components"]:
        binaries.append(component.get("binary", component["crate"]))
    return binaries


def render(variant: str) -> str:
    binaries = load_binaries()
    staging = "packaging/staging" if variant == "prod" else "packaging/staging-dbg"
    if variant == "prod":
        name = "cdt"
        section = "net"
        description = """\
Cole's DNS Tools — DNS utility bundle.
Production package with stripped binaries.
"""
    else:
        name = "cdt-dbg"
        section = "debug"
        description = """\
Cole's DNS Tools debug binaries (unstripped) for troubleshooting.
"""

    lines = [
        f"# Generated by {Path(__file__).name}; do not edit.",
        f"name: {name}",
        "arch: amd64",
        "platform: linux",
        'version: "${VERSION}"',
        f"section: {section}",
        "priority: optional",
        'maintainer: "CDT Maintainers <cole@tuininga.org>"',
        "description: |",
    ]
    for line in description.strip().splitlines():
        lines.append(f"  {line}")
    lines.extend(
        [
            "license: Apache-2.0",
            "homepage: https://github.com/egon1024/cdt",
            "rpm:",
            "  group: Applications/Internet",
            "contents:",
        ]
    )
    for binary in binaries:
        lines.extend(
            [
                f"  - src: {staging}/usr/bin/{binary}",
                f"    dst: /usr/bin/{binary}",
            ]
        )
    if variant == "prod":
        lines.extend(
            [
                "  - src: LICENSE",
                "    dst: /usr/share/doc/cdt/copyright",
                "  - src: docs",
                "    dst: /usr/share/doc/cdt/docs",
                "    type: tree",
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--variant",
        choices=("prod", "dbg"),
        required=True,
        help="Production (stripped) or debug package",
    )
    args = parser.parse_args()
    sys.stdout.write(render(args.variant))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
